#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User


# config/packages/easy_admin.yaml
easy_admin:
  entities:
  # change the following to the namespaces of your own entities
    - App\Entity\User
    - App\Entity\Films
    - App\Entity\Screenings
    - App\Entity\Room
    - App\Entity\Booking
